#数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.200.6:3306/msg-middleware?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: $2a$10$zJs3WvLM1zG2CC4QJVlDBeQn2aoJndl1qew5yc.wymOTQdPwQjG9W
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    sql-script-encoding: utf-8
    platform: mysql